# Generated by Django 3.0.7 on 2020-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyperdate',
            name='nominal',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
