# Generated by Django 3.0.7 on 2020-06-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currencyperdate_nominal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyperdate',
            name='main',
        ),
        migrations.RemoveField(
            model_name='currencyperdate',
            name='sub',
        ),
        migrations.AddField(
            model_name='currencyperdate',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='currency.Currency'),
            preserve_default=False,
        ),
    ]
