# Generated by Django 3.0.7 on 2020-06-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20200628_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyperdate',
            name='nominal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyperdate',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
